// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLj-FUnE_0Shgb3zdLnDEcy_Ma-VaVhIM',
    appId: '1:512678863892:web:d709c9d078ceeacdfbb301',
    messagingSenderId: '512678863892',
    projectId: 'ageapp-e65d8',
    authDomain: 'ageapp-e65d8.firebaseapp.com',
    storageBucket: 'ageapp-e65d8.firebasestorage.app',
    measurementId: 'G-TMSKXZVX63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNH8nxv-c1o6zG6AeFwmsEAjbjhOXsdy8',
    appId: '1:512678863892:android:c71370f857725ecbfbb301',
    messagingSenderId: '512678863892',
    projectId: 'ageapp-e65d8',
    storageBucket: 'ageapp-e65d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPA0m8nlYRLgEy2E4gbWxmh7uB0hc_0kw',
    appId: '1:512678863892:ios:61c741fab5f38ba5fbb301',
    messagingSenderId: '512678863892',
    projectId: 'ageapp-e65d8',
    storageBucket: 'ageapp-e65d8.firebasestorage.app',
    iosBundleId: 'com.example.ageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPA0m8nlYRLgEy2E4gbWxmh7uB0hc_0kw',
    appId: '1:512678863892:ios:61c741fab5f38ba5fbb301',
    messagingSenderId: '512678863892',
    projectId: 'ageapp-e65d8',
    storageBucket: 'ageapp-e65d8.firebasestorage.app',
    iosBundleId: 'com.example.ageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLj-FUnE_0Shgb3zdLnDEcy_Ma-VaVhIM',
    appId: '1:512678863892:web:96fd3f02e2aff091fbb301',
    messagingSenderId: '512678863892',
    projectId: 'ageapp-e65d8',
    authDomain: 'ageapp-e65d8.firebaseapp.com',
    storageBucket: 'ageapp-e65d8.firebasestorage.app',
    measurementId: 'G-1JQFK5SZL4',
  );

}